### ISSUE TITLE
Reduce the significant digits on the altitude selection (easy!)

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#124]
The number of significant digits on the altitude selection should be to the millimeter scale, not more.  For example:   `3.045 m`.   Currently there are so digits that it makes us look silly:
![2015-10-28_7-07-24](https://cloud.githubusercontent.com/assets/1872600/10786894/57949400-7d43-11e5-9562-06a5cc8b4cab.png)

@emontgomery-usgs, also do we really have two velocity sensors this close in altitude in this dataset?   Unless these are sensors for the trowbridge turbulence method, it seems suspicious.

**Comment by emontgomery-usgs** [comment]
@rsignell-usgs, yes, we did have multiple sensors at very close to the same height on this platform, a flo-bee. We've been deploying 2 platforms like this in most of Warners experiments since ~2006, and Sherwood's Tripods are like this too.

Here's how it maps from the Bottom up-
1) downward looking PCADP or HF-AQD gets the bottom 1.5 meters at ~10 cm vertical spacing
2) 2 ADVs at the same height, in the measurement range of the PCADP
3) (no measurements for ~1.5m)
4) upward looking ADCP, 3m from bottom to surface, at ~.5m spacing

I haven't done the math but am guessing at least 20 possible current measurement elevations, given all the different kinds of sensors on the platform.

These platforms will also have temperature, salinity, pressure and turbidity at multiple heights.

I'm not sure what we should do (if anything) about selecting for quality here.  Since there's no sensor type tagged to the elevation how does the user knot which sensor the data came from in order to assess if they want to use it?  For instance, a user wouldn't want to use the temperature in Tx_1211 on the ADCP, if T_28 was available from a Seacat of Microcat.  Similarly, the Pressure from the paros sensors attached to the ADV is "better" the a pressure from a Seacat or Microcat.

Another set of issues to deal with, but I think the altitudes are correct here, if a negative sign is added (the user doesn't know if we're using z-positive "up" or "down"), and the significant digits cropped.  I'm fairly sure this data is from ~14 meters depth, and with the positive sign, I would expect this data to be in air.

Thanks! Ellyn

**Comment by kwilcox** [comment]
Significant digits issue was solved in the issue regarding FillValues not carrying though (I was converting float32 to float64).  They will be fixed on next iteration of the dataset.

If you click the "Parameters" link it will tell you which file each time-series came from. Is that enough to distinguish which temperature sensor to use?

**Comment by emontgomery-usgs** [comment]
@kwilcox I think it all depends on what you guys are trying to provide; quick look visualization, or an in-depth tool for selection and analysis.

If the former, I think we should do more curation of what gets displayed, and select "best" sources from data available.  If the latter, then perhaps, 
* the parameters link could be made more obvious
*  "discriminant" could be changed to "instrument type"
* populate this field with the global attribute "INST_TYPE" instead of file name

In the screenshot below, the information available isn't enough to let anyone except possibly me make a "reasonable" decision on which of the temperature data to use.
![portal_params](https://cloud.githubusercontent.com/assets/1771422/10818926/92d6c9ce-7e1b-11e5-8f86-05a8b9791184.png)

**Comment by kwilcox** [comment]
Sig figs are fixed on the (many) stations I tested

**Comment by rsignell-usgs** [comment]
Yes, looking good:
![2016-02-02_6-06-36](https://cloud.githubusercontent.com/assets/1872600/12747672/5e415cd0-c973-11e5-8568-33ee0e33eee8.png)

**Comment by rsignell-usgs** [comment]
But that Altitude should be `-1.2`, not `1.2`.   Opened as issue #144.

**Comment by rsignell-usgs** [comment]
Wait a minute.  The other sensor at this location still has the silly number of sig figs.   
![2016-02-02_6-24-32](https://cloud.githubusercontent.com/assets/1872600/12748107/257d7b9c-c976-11e5-86f0-0dc84685beaa.png)

**Comment by kwilcox** [comment]
@rsignell-usgs This is the value that is in the raw files I'm converting to CF:

```
float Tx_1211(time, lat, lon) ;
                Tx_1211:name = "Tx" ;
                Tx_1211:long_name = "instrument Transducer Temp." ;
                Tx_1211:generic_name = "temp" ;
                Tx_1211:units = "degrees.C" ;
                Tx_1211:epic_code = 1211 ;
                Tx_1211:sensor_type = "Nortek Aquadopp Profiler" ;
                Tx_1211:sensor_depth = 1.27543386223034 ;
                Tx_1211:initial_sensor_height = 0.17 ;
                Tx_1211:height_depth_units = "m" ;
                Tx_1211:serial_number = "AQD 6409" ;
                Tx_1211:minimum = 23.26f ;
                Tx_1211:maximum = 28.17f ;
                Tx_1211:valid_range = "" ;
                Tx_1211:_FillValue = 1.e+35f ;
```

http://geoport.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/Data/WFAL/9391aqd-cal.nc.html

**Comment by rsignell-usgs** [comment]
Okay, so we could fix this on our end.   But can't you easily fix (truncate) this when you convert to CF-1.6? 
Certainly 1mm 0.001m should be enough accuracy!

**Comment by kwilcox** [comment]
I can... but the conversion to CF has been designed not to change **any** data up to this point. It feels like we are short-cutting if we start truncating data in special cases now. Let me know what I should do.

**Comment by kwilcox** [comment]
Fixed in https://github.com/USGS-CMG/usgs-cmg-portal/commit/92a7116a91846806766656730e8e9f7c73cb10c1, will wait for new file import before closing

**Comment by kwilcox** [comment]
Fixed in the files, but there is still a problem with our services... fixing...

**Comment by kwilcox** [comment]
@rsignell-usgs please test this again

**Comment by rsignell-usgs** [comment]
Yep, fixed!
![2016-03-01_9-40-59](https://cloud.githubusercontent.com/assets/1872600/13430160/e0e2e2f6-df91-11e5-8aa5-58c4a229da03.jpg)
