### ISSUE TITLE
run076 Barnegat Bay bed_thickness layer data do not display

### ISSUE THREAD

**Issue by zdefne-usgs** [USGS-CMG/usgs-cmg-portal#158]
The portal displays broken tiles (within beyond the extent of the model domain) for bed_thickness. Below image shows  the zeta layer displayed properly, while bed_thickness is not. 

![croppercapture 65](https://cloud.githubusercontent.com/assets/4505315/12864835/b9c07dba-cc67-11e5-8ed3-db0a459c4bf5.png)

**Comment by rsignell-usgs** [comment]
I looked at the layer attributes for the `bed_thickness` variable here:
http://geoport-dev.whoi.edu/thredds/dodsC/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml.html
and they look okay.   

@kwilcox, Is the problem that there is no default color range defined?

If so, perhaps @zdefne-usgs could try adding attributes for the color range for that variable and we could see if that fixes the problem.

**Comment by rsignell-usgs** [comment]
Here's the portal URL 
http://cmgdata.usgsportals.net/#map?p=proj3857&b=google_hybrid&page=1&tagId=&q=&lg=3ffaf561-2ba6-4e3c-97cd-75566b58e7ff&z=10&ll=39.79358%2C-74.22003

**Comment by kwilcox** [comment]
The `bed_thickness` layer is not advertised in your WMS GetCaps:

http://geoport-dev.whoi.edu/thredds/wms/clay/usgs/users/zdefne/run076/his/00_dir_roms_display.ncml?service=WMS&version=1.3.0&request=GetCapabilities

**Comment by kwilcox** [comment]
I raised the same issue back in December: https://github.com/USGS-CMG/usgs-cmg-portal/issues/6

I knew this sounded familiar!

**Comment by rsignell-usgs** [comment]
Perhaps there is some arbitrary limit on the number of WMS layers? Okay, I'll pick this up with Unidata. 

The bed_thickness works just fine with netcdf-java:
![2016-02-09_11-32-28](https://cloud.githubusercontent.com/assets/1872600/12923413/a49c4888-cf23-11e5-8684-e3231cd143b2.png)

**Comment by rsignell-usgs** [comment]
Okay, this wasn't a Unidata problem afterall.  Basically the bed layer variables were not CF compliant since they have multiple vertical layers (a vertical dimension), but there was no vertical coordinate variable.   Our fix for this has been to add a pseudo vertical coordinate variable `Nbed` in the NcML thusly:
```
     <variable name="Nbed" shape="Nbed" type="double">
      <attribute name="long_name" value="pseudo coordinate at seabed points"/>
      <attribute name="standard_name" value="ocean_sigma_coordinate"/>
      <attribute name="positive" value="up"/>
      <attribute name="formula_terms" value="sigma: Nbed eta: zeta depth: h"/>
      <values start="-1.0" increment="-0.01"/>
     </variable>
```
and this fixed the problem:
![2016-02-09_15-19-17](https://cloud.githubusercontent.com/assets/1872600/12929903/73b80d0e-cf43-11e5-86fb-183ea8bc52a5.png)

I just added the above lines for to the NcML as a test, but I will add this to the `yaml2ncml` script so that we don't have this problem in the future.
