### ISSUE TITLE
External accessibility of viz?

### ISSUE THREAD

**Issue by mhines-usgs** [USGS-CMG/usgs-cmg-portal#177]
How accessible are the visualizations and products in the [Oceanographic Portal](http://cmgdata.usgsportals.net/) (OP)?
Can can we pull them into the [Coastal Change Hazards Portal](http://marine.usgs.gov/coastalchangehazardsportal) (CCH) easily?

Specifically the time series pop outs from the OP, as users click on the bacon strips? Total wave heights, scenarios, etc. If we were to pass a lat/long click from the user, could we embed the response/output from the OP for that location into the CCH in a popup or ?

**Comment by rsignell-usgs** [comment]
The "bacon strips" @mhines-usgs is talking about are these maps from the CCH:
![2016-03-14_22-25-12](https://cloud.githubusercontent.com/assets/1872600/13765976/70903b90-ea34-11e5-9899-25d1e2260ba6.jpg)

**Comment by rsignell-usgs** [comment]
@mhines-usgs , I think it would be possible because such time series plots like this one:
![2016-03-14_22-49-49](https://cloud.githubusercontent.com/assets/1872600/13766333/52f958d4-ea37-11e5-8f0b-274f75afc59c.jpg

is a data request like this that returns JSON:
http://pdx.axiomalaska.com/stationsensorservice/getDataValues?sensorid=9&stationid=45476&convertDatesToInt=1&pastHours=168&version=2&units=14;millibars&method=GetSensorObservationsJSON&jsoncallback=_jqjsp&_1458010103646=

**Comment by kwilcox** [comment]
I would push towards the ERDDAP endpoints we have for every stations. Would that work?

**Comment by rsignell-usgs** [comment]
@kwilcox, yes, better solution, using the JSON response.   @mhines-usgs and other web devs could get some inspiration (ripping off code?) from the ERDDAP-driven web app here: http://www.digitalocean.ie/Dashboard/Mayo
