### ISSUE TITLE
Time slider controls are missing for this dataset

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#214]
http://cmgdata.usgsportals.net/#module-metadata/590b5a22-b61e-11e4-b2db-00265529168c/6878f136-b61e-11e4-a8f5-00265529168c

![2016-06-21_14-17-11](https://cloud.githubusercontent.com/assets/1872600/16241402/75fa475e-37bb-11e6-8e75-b99178be976f.jpg)

What causes this problem?

**Comment by kwilcox** [comment]
It appears that if the entire data-set can comfortably fit on the graph/screen then the time slider controls go away. This seems like a bug. @akbstone can you look into this?

**Comment by akbstone** [comment]
@rsignell-usgs, @kwilcox 

This has been fixed in the new charts interface:

http://cmgdata.usgsportals.net/?use_new_charts=true#map?p=proj3857&b=google_hybrid&lg=6878f136-b61e-11e4-a8f5-00265529168c&z=19&ll=41.60472%2C-70.64379

![image](https://cloud.githubusercontent.com/assets/1093777/17606790/e17a71d6-5fcd-11e6-9546-00322dcb89b7.png)
