### ISSUE TITLE
Add sample PCMSC data from RIVET II experiment

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#216]
Via email, Andrew Stevens (USGS, Santa Cruz) wrote: "In 2013, a few of us from USGS (Guy Gelfenbaum, myself, and Chris Sherwood) participated in the ONR-funded RIVET II experiment in the mouth of the Columbia River.  The field data collection was quite successful and we have some cool time-series data in a very dynamic setting.  I have been working with Guy and Edwin Elias (Deltares USA) to improve our coupled Delft3D-SWAN model of the region and have applied the model for the time period of the field experiment (about 40 day hindcast).  The combination of data and modeling from this experiment seems like a natural fit for the portal.  "

This indeed would be cool to add.   We don't have any Delft3D data in the portal yet, but our CF and SGRID standards should support it.

**Comment by rsignell-usgs** [comment]
@drewstev, can you put some ADCP data on google drive as a 1st step.  Is that possible?

**Comment by drewstev** [comment]
@rsignell-usgs , yep, I just shared our adcp and ctd data via google drive. Thanks!

**Comment by drewstev** [comment]
For D3D model output, I dug up this in my email from Bert Jagers (Deltares) on creating netcdf files: 

"There are three options for creating NetCDF files for Delft3D simulations.
 
1)    Write Delft3D output directly to NetCDF. This would be the preferred way moving towards the future. Delft3D-FLOW revisions after 4649 (February 2015) have this feature. By adding the line FlNcdf = #map his dro fou# you will get the map (trim), history (trih), and drogue (trid) output in NetCDF instead of default NEFIS format and the fourier (fou) data in NetCDF instead of ASCII. The advantage is that the output is directly written to NetCDF file and hence readable by other tools, but the disadvantage is that QUICKPLOT is not yet able to plot all the derived quantities in the same way for the NetCDF files as it is for the default NEFIS files.

2)    The VS_TRIM2NC MATLAB function allows you to convert the trim-file to NetCDF. It includes a lot of features, but it is a community product and not officially supported. The main drawback is that you need a MATLAB license.

3)    The delft3d_to_netcdf.exe tool is a Fortran program that is based on a tool that was developed by the Dutch ministry of Infrastructure for converting the data written by WAQUA/SIMONA (another Dutch 2D/3D hydrodynamic model very similar to Delft3D). I reused that code because at the time the intention was to integrate these two models. Unfortunately, I wasn’t able to release this program in source code even though the source code indicated otherwise, so I basically stopped the development several years ago. The integration of the two models has been replaced by the shared development of the new Flexible Mesh code. I have a Windows version of this program that is still fairly functional, but the MATLAB function is more easy to adjust"

I am going to try option 1) after upgrading my Delft3d version and get back to you with the output.

**Comment by rsignell-usgs** [comment]
Excellent.  Thanks!   It looks like it might be possible to convert using python also:
https://github.com/GrumpyNounours/Nefis2netcdf

**Comment by rsignell-usgs** [comment]
@kwilcox , we would like to try converting some files from our sister CMG office in Santa Cruz, and not surprisingly, they don't use Woods Hole naming conventions.   Can you modify the filtering rules to allow these files to be converted?
http://geoport.whoi.edu/thredds/catalog/usgs/data2/rsignell/stellwagen/Data/RIVET2/catalog.html
(and just out of curiousity, where are these filtering rules implemented?) 
Would it be possible to load them from a config file like the CSV file of experiment metadata?

**Comment by drewstev** [comment]
@rsignell-usgs I put some D3D model output in .nc format in the Google Drive area to start playing with it.  I used the VS_TRIM2NC matlab code that Bert mentioned (option 2) for a small subset in time (4 days) and variables (water levels, velocities, and salinity) so the file was a reasonable size. 

Let me know if the file would need any adjustments...I can easily edit the code that converts from NEFIS to .NC

**Comment by rsignell-usgs** [comment]
We have  different types of data to display here:
- [ ] time series data that are EPIC, but don't follow Woods Hole numbering system #217
- [ ] Delft3D (D3D) Model data, on curvilinear grid #218

**Comment by kwilcox** [comment]
@rsignell-usgs can we close this now that the two datasets have their own issues?

**Comment by rsignell-usgs** [comment]
Issues moved to #217 and #218
