### ISSUE TITLE
hudson fields not populating

### ISSUE THREAD

**Issue by nganju-usgs** [USGS-CMG/usgs-cmg-portal#225]
This catalog entry doesn't seem to be loading the fields. Thumbnails are kind of greyed out too...

http://cmgdata.usgsportals.net/#module-metadata/17d1d851-1e74-3602-a1c3-8fb58ae5bd96/324fac10-d0a3-4067-ae42-9e1377414800

**Comment by rsignell-usgs** [comment]
@kwilcox , I was going to look into this issue by checking the OPeNDAP URL to make sure it's working, but how do I tell what the endpoint is from the portal.    There should be some "info" tab about this layer/dataset/item, right?

**Comment by kwilcox** [comment]
Try the "Download" button. Layer working for me

**Comment by rsignell-usgs** [comment]
Probably the reason @nganju-usgs and I thought it wasn't working is because it take so long to load an image.   Nearly 1 minute to produce the plot shown below.   This data is being served by Clancy at WHOI.  Perhaps the disk and/or internet speed to this machine is slow?
![2016-08-18_11-24-00](https://cloud.githubusercontent.com/assets/1872600/17779685/85cd26e4-6536-11e6-95d4-4173d9cf97de.jpg)

**Comment by zdefne-usgs** [comment]
I had the same confusion  yesterday. A spinning wheel or a "loading..." message until the tiles starts loading might be helpful. 
While playing around I also realized that the Download->Opendap in catalog view returns with error message. 
Error {
    code = 400;
    message = "Unrecognized request";
};

**Comment by rsignell-usgs** [comment]
@zdefne-usgs , I like the idea of a spinning wheel, loading, or something would be good.

Regarding that 400 error, it's because it's an OPeNDAP data link that doesn't open in a browser.   Try adding a '.html' on the end to get the dataset access page, or a '.dds' to get the dataset description.

**Comment by kwilcox** [comment]
@rsignell-usgs OK to close?

**Comment by rsignell-usgs** [comment]
Yep, it's slow, but working.
