### ISSUE TITLE
Please have "catalog" link not bring up sensor stations

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#272]
Right now the "catalog" link on cmgdata.usgsportals.net brings up:

https://cmgdata.usgsportals.net/#module-search?page=1&tagId=&q=&tags=&types=module%2Csensor_station%2Cproject

which overwhelms the user with sensor stations:

![2018-03-05_9-21-37](https://user-images.githubusercontent.com/1872600/36979841-ad329ca0-2056-11e8-8086-0cd2534067e6.png)

 Could you please make it point to

https://cmgdata.usgsportals.net/#module-search?page=1&tagId=&q=&tags=&types=module

instead:
![2018-03-05_9-23-11](https://user-images.githubusercontent.com/1872600/36979922-e68d5c7e-2056-11e8-9a5b-edd3e4eee5e1.png)

**Comment by rsignell-usgs** [comment]
@lucmehl, is this one you can handle also?

**Comment by lucmehl** [comment]
We've got a ticket for better "Sensor stations" filter functionality, but that is a ways off. The problem with setting the "Sensor stations" to "off" by default is that users won't know that they need to select the box for stations to show up as search results.

In the short term, I've given the modules a higher rank order so that the stations are at the bottom of the list. Let me know if this is an acceptable solution for now.

**Comment by rsignell-usgs** [comment]
@lucmehl, I'm not sure we have any data in this portal that you call "sensor stations".   The only sensor data we have are contained in these two datasets:

https://cmgdata.usgsportals.net/#module-search?page=1&tagId=&q=time%2520series&tags=&types=module

So I think you __could__ turn that "sensor stations" filter to off, no?

**Comment by lucmehl** [comment]
@rsignell-usgs , let's make sure we are on the same page with terminology.

Your first screen capture has `Sensor stations` SSS-NJ-OCE-001 and SSS-VA-VAB-001. There are 900+ of this type of station in the catalog.

The catalog has two modules with the tag `Sensors` (USGS Hurricane Sandy Rapid Response Gauges, U.S. Geological Survey Oceanographic Time-Series Measurement Database). These modules each contain a set of `Sensor stations`.

The problem is that the user is overwhelmed by the 900+ `Sensor Stations`. The options are:

* Don't allow users to find the individual `Sensor stations` in the catalog. This makes the assumption that users will only be interested in viewing the stations that are contained in one of the two `Sensors` groupings.
* List the 900+ stations after the 16 modules/layer groups that the users are most likely to be looking for (this is how the catalog is currently set up).
* Find a better solution to filter/distinguish stations, layers, groups of stations, etc. This is on the Axiom to-do list, but will not be ready soon.

So I guess the question is... will a user ever want to look up an individual station in the catalog?

**Comment by rsignell-usgs** [comment]
It's okay now the way it is.  I didn't realize those stations were in our time series database.
