### ISSUE TITLE
USGS logo for data ID

### ISSUE THREAD

**Issue by bbutman-usgs** [USGS-CMG/usgs-cmg-portal#60]
When mousing over data points in the USGS time-series data base, the B&W USGS logo appears in a circle.   I've only seen it as a square.  More 'recognizable' , background USGS green, wavy lines white.

![usgs_id348_cropped](https://cloud.githubusercontent.com/assets/11786524/7049844/ef0ce6a0-ddea-11e4-8430-cbc60f0ff7b8.jpg)

Or use a standard USGS logo, but Rich says too much.  

![id348sm](https://cloud.githubusercontent.com/assets/11786524/7049443/80f3a8dc-dde7-11e4-9e2d-d4dc50c706f5.jpg)

**Comment by rsignell-usgs** [comment]
From looking at several of these popups:
![4-10-2015 7-31-23 am](https://cloud.githubusercontent.com/assets/1872600/7086901/0af483e0-df54-11e4-92aa-a93b8501f4de.png)

![4-10-2015 7-30-04 am](https://cloud.githubusercontent.com/assets/1872600/7086881/ee5a1178-df53-11e4-8931-72fb424ee541.png)


It looks like the decision was made to crop icons to a circle.   That looks great for NOAA and others that use circular icons, but doesn't work well for others, like USGS.

How about just cropping to a square instead of a circle?

**Comment by emontgomery-usgs** [comment]
@kwilcox , @rsignell-usgs @dnowacki-usgs 

Can this topic be prioritized?  For our visual identity and branding, the logo really needs to be green, and clearly color is OK, since NOAA is blue and ACE has a red castle.

Would it help if we supplied the icon to fit in the specified pixel space required?

**Comment by kwilcox** [comment]
We can use https://en.wikipedia.org/wiki/File:USGS_logo_green.svg, I've asked Brian and John to update this on our end.

**Comment by emontgomery-usgs** [comment]
Many thanks!

**Comment by emontgomery-usgs** [comment]
@kwilcox @rsignell-usgs @dnowacki-usgs 

The green logo looks great on the IOOS portal now, Thanks!
