### ISSUE TITLE
Allow setting color range limits beyond the default range

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#64]
We need to allow the user to specify the color range limits outside the default range.  Below I tried to set the lower bound for salinity to 28, lower than the default minimum range of 30, but this had no effect.    We need this in the situations as displayed below, where much of Barnegat Bay is black (below the minimum value of 30) and we need to change it.
![4-13-2015 5-15-57 pm](https://cloud.githubusercontent.com/assets/1872600/7125711/3130d6c6-e201-11e4-99f5-31bf112b327b.png)

**Comment by kwilcox** [comment]
This is on our to-do list.  Right now the single min/max values for each variable control the default values for the colorscale **and** the window of selectable values.  They will be changed to only control the default values. The selectable values will be pulled from "sanity" checks based on parameter rather than a specific model/variable.

**Comment by kwilcox** [comment]
This requires https://github.com/USGS-CMG/usgs-cmg-portal/issues/75

**Comment by kwilcox** [comment]
This is fixes, the values can be edited outside of the defaults.
