### ISSUE TITLE
Can't get time series from model result (WMS getFeatureInfo)

### ISSUE THREAD

**Issue by rsignell-usgs** [USGS-CMG/usgs-cmg-portal#86]
I'm trying to figure out how to click and get a time series on a map from a model simulation like this [salinity from Sandy](http://cmgdata.usgsportals.net/#map?lg=53bb506f-11bd-436e-94c6-83e42f763e35&p=proj3857&b=google_hybrid).

In NcWMS/Godiva2, if the user clicks on a spot, they get a pop up with the value, but if they have specified a start time and a stop time, then when they click a spot, they get a pop up that says "time series" which returns the time series. 

If I click a point I get back the value.   I'm not sure how to set a time range and see a time series.

We can't in general default to extracting the entire time series, as we have some datasets that have hourly data for 30 years.

**Comment by rsignell-usgs** [comment]
Could we have the default behavior be a bit like godiva2?    
E.g. click on a map, get a popup with value and location, but then with option to do a time series.  And maybe the default range on the time series would be -3/+3 days from the current location on the time slider?

**Comment by rsignell-usgs** [comment]
@lance-axiom, were you working on this?  
Are we going to make it for the demo tomorrow?

**Comment by lance-axiom** [comment]
@rsignell-usgs, Yes, I have finished adding this feature. You can test it out now. It only works for the above model. If there are other models that we want this to work for I can add those also.

**Comment by rsignell-usgs** [comment]
@lance-axiom, great!  I confirmed that it's working for this dataset. Here's proof:
![2015-10-22_14-16-45](https://cloud.githubusercontent.com/assets/1872600/10674183/a4746ae6-78c7-11e5-868f-51393d1cca4b.png)

Why does it need to be enabled on a case-by-case basis?

Can you tell me a bit more about what is going on here?   
I see the URL called by the app is:

http://servomatic9000.axiomalaska.com/ncWMS-utils/getFeatureInfo?callback=jQuery1111043004183288738607_1445537883822&times=1351843200000&y=217&x=354&height=436&width=1024&epsg=3857&uuids=a96c8b50-3b59-401d-ad61-105e3be90c8b&bbox=-8306106.0319081%2C4849431.2702619%2C-7993019.9640956%2C4982737.4475727&elevations=null&units=null&_=1445537883826

Is this a pass-through to the WMS-services running on our machine?
I just want to make sure that this is using the services here at USGS, not at Axiom.  Unless it's just a stop-gap for the demo tomorrow.

**Comment by rsignell-usgs** [comment]
Eventually perhaps we could use NCSS if it's available for these datasets.  Check out the response time of this!

http://geoport-dev.whoi.edu/thredds/ncss/clay/usgs/users/jcwarner/Projects/Sandy/triple_nest/00_dir_NYB05.ncml?var=zeta&latitude=40.48&longitude=-73.82&time_start=2012-10-25T00%3A00%3A00Z&time_end=2012-11-02T08%3A00%3A00Z&vertCoord=&accept=csv

Too bad they don't have json as an output format yet.  I think it's on the to-do list for Unidata.

**Comment by lance-axiom** [comment]
@rsignell-usgs 

The call is actually below:
http://pdx.axiomalaska.com/virtualsensor/getDataValues?jsoncallback=_jqjsp&method=GetSensorObservationsJSON&layer_uuid=53bb506f-11bd-436e-94c6-83e42f763e35&depth=-0.03125&lat=40.22266002734742&lon=-73.55895996322944&maxresults=200&start_time=1351123200&end_time=1351843200&jsoncallback=?&_1445540492680=

This calls an axiom service that connects through your OPeNDAP service to collect the data. I need to add each one individually because I need to get that models OPeNDAP URL for example :http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data0/mvco_ce/mvco_output/spatial_7_ar0fd/00_dir_roms.ncml.

**Comment by rsignell-usgs** [comment]
@lance-axiom, are we using opendap instead of NCSS because opendap is more standard?   Just would like to be brought in on the design/performance issues on this one.    

On the face of it, NCSS would seem a good fit for this job because it's a RESTFUL URL that already takes lon,lat, variable and time range and gives back data in a form digestible by javascript.

**Comment by lance-axiom** [comment]
@rsignell-usgs I am using OPeNDAP because it was the cleanest and fastest way to integrate using external THREDDS servers into the service. This is not a new service that works only for external THREDDS servers. It is the same existing service the axiom uses for all of its local netcdf models. We can later look into increasing the speed of the requests for the external THREDDS connections. I already know a few things I can be done to increase the speed.

**Comment by rsignell-usgs** [comment]
@lance-axiom , awesome, thanks for the explanation.
